### ISSUE TITLE
Regression when failure while adding nodes

### ISSUE THREAD

**Issue by EmmEff** [UnivaCorporation/tortuga-kit-gceadapter#31]
```shell
[2018-09-04 13:06:56,957: ERROR/ForkPoolWorker-3] Cleaning up failed instance [*-kdhgp] (node [*-kdhgp.c.unicloud-devel.internal])
[2018-09-04 13:06:56,957: DEBUG/ForkPoolWorker-3] __node_cleanup(): node=[*-kdhgp.c.unicloud-devel.internal]
[2018-09-04 13:06:56,961: DEBUG/ForkPoolWorker-3] Unlocking session lock
[2018-09-04 13:06:56,961: ERROR/ForkPoolWorker-3] Exception occurred during add host workflow
Traceback (most recent call last):
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/resourceAdapter/gce.py", line 1303, in __addActiveNodes
    session, dbSession, node_request_queue, addNodesRequest)
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/resourceAdapter/gce.py", line 1032, in __launch_instances
    persistent_disks=persistent_disks, preemptible=preemptible)
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/resourceAdapter/gce.py", line 1482, in __launch_instance
    zone=config['zone']
  File "/opt/tortuga/lib64/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/tortuga/lib64/python3.6/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/unicloud-devel/zones/us-east1-b/instances?alt=json returned "Invalid value for field 'resource.name': '*-kdhgp'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/addhost/addHostRequest.py", line 56, in process_addhost_request
    ahm.addHosts(session, addHostRequest)
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/addhost/addHostManager.py", line 92, in addHosts
    dbSoftwareProfile=dbSoftwareProfile)
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/resourceAdapter/gce.py", line 246, in start
    dbHardwareProfile, dbSoftwareProfile)
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/resourceAdapter/gce.py", line 1307, in __addActiveNodes
    self.__post_launch_action(dbSession, session, node_request_queue)
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/resourceAdapter/gce.py", line 1335, in __post_launch_action
    self.__node_cleanup(node_request['node'])
  File "/opt/tortuga/lib64/python3.6/site-packages/tortuga/resourceAdapter/gce.py", line 528, in __node_cleanup
    bhm = osUtility.getOsObjectFactory().getOsBootHostManager()
TypeError: getOsBootHostManager() missing 1 required positional argument: 'configManager'
```

**Comment by EmmEff** [comment]
Also affects node deletion
